### ISSUE TITLE
[Feature Add] Integrate Jokes API for Humorous Dictionary Experience

### ISSUE THREAD

**Issue by Ishfaq24** [aqib-m31/Jokesaurus-The-Hilarious-Dictionary#1]
## Description
As part of enhancing our dictionary application, we can integrate a Jokes API to add a touch of humor and entertainment to the user experience. This will allow users to not only search for word definitions but also enjoy a good laugh while using our application.

**Comment by unnatijp24** [comment]
That's a good add on! I guess this can help us :  **https://jokeapi.dev/**

**Comment by aqib-m31** [comment]
Sounds good! Let me start working on it.

**Comment by unnatijp24** [comment]
so what are you planning to add?🤓

**Comment by aqib-m31** [comment]
> so what are you planning to add?🤓

Fetching a Joke from Jokes API each time user searches a word!
