### ISSUE TITLE
[Fix] Audio appears when no audio is found.

### ISSUE THREAD

**Issue by Ishfaq24** [aqib-m31/Jokesaurus-The-Hilarious-Dictionary#18]
**Describe the bug**
When I tried to search hackathon, `Audio: ` appears with no buttons.

**Expected behavior**
If no audio is found, `Audio:` shouldn't appear.

**Comment by aqib-m31** [comment]
@Ishfaq24 Thanks for raising an issue. Lemme work on it.

**Comment by aqib-m31** [comment]
@Ishfaq24 Fixed and Closed!
