### ISSUE TITLE
Feature Request: Add light/dark mode

### ISSUE THREAD

**Issue by You-now-Who** [aqib-m31/Jokesaurus-The-Hilarious-Dictionary#2]
# Description

Looking for the addition of the option to switch from dark mode to light mode in the website.

**Comment by unnatijp24** [comment]
that's a great idea @You-now-Who! lemme work on this

**Comment by aqib-m31** [comment]
@unnatijp24 Go for it! Design the UI and also add this feature.

**Comment by aqib-m31** [comment]
@unnatijp24 lol.png is missing!
