### ISSUE TITLE
random jokes are appearing

### ISSUE THREAD

**Issue by unnatijp24** [aqib-m31/Jokesaurus-The-Hilarious-Dictionary#4]
The API is producing random funny jokes😂😂. But could it be more optimized?

**Comment by aqib-m31** [comment]
Lemme checkout, if there's some room for optimizing!

**Comment by unnatijp24** [comment]
yes! Here you can bring content related to the word searched or something like that. 🤓

**Comment by aqib-m31** [comment]
Yep, there's an option for including a word as a part of query string and getting a joke that contains the same word!
The thing is if the user inputs some gibberish or blank word! We'll have to handle those situations! Lemme figure out how can I make it work!

**Comment by aqib-m31** [comment]
@unnatijp24 Lemme first try fixing this issue, you can then work on design part!
